### ISSUE TITLE
Chrome Store link in README gets 404

### ISSUE THREAD

**Issue by zwbetz-gh** [felicianotech/hugo-browser-extension#1]
Hi there - the Chrome Store link (below) in the README brings me to a 404 page

https://github.com/felicianotech/hugo-browser-extension/blob/master

I'm thinking it should be this instead?

https://chrome.google.com/webstore/detail/hugo-the-extension-you-re/hbaembbfbmpbjgkgcjcfonnimlekbfea/

**Comment by FelicianoTech** [comment]
You're correct, thank you. I'll fix it as soon as I get back to my laptop.
